ICV_HOME_DIR      = /p/foundry/eda/em64t_SLES11/icvalidator/J-2014.06-SP2-1
WORKING_DIR       = .
INLIB             = ../../apr/outputs/fdkex.apr.oas
INLIB_PATH        = 
OUTLIB            = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/fdkex
OUTLIB_PATH       = .
BLOCK             = fdkex
PYDB_PATH         = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/pydb
RUN_DETAILS_DIR   = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936
NDB_PATH          = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/.ndb
FORMAT            = OASIS
EVACCESS_PATH     = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/pydb
SCHEMATIC         = ../fdkex.icv
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/group
RUNSET_FILE_NAME  = trclvs.rs
ENVIRONMENT STRING  PROJECT = fdk73
EXTRACTION_FLOW   = true
COMPARE_DIR       = /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_trclvs_run_details_18936/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
