#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_drcd_run_details_18936 | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /nfs/ch/disks/icf_fdk_regression001/nightly_adf_kit_build_regr/builds_regr/nightly/1273/dot3/synopsys/2015-03-31/runs/d04/fdkex_SCAN/drc_lvs/drcd/fdkex.TOP_LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /nfs/ch/disks/icf_fdk_regression001/nightly_adf_kit_build_regr/builds_regr/nightly/1273/dot3/synopsys/2015-03-31/runs/d04/fdkex_SCAN/drc_lvs/drcd/fdkex.TOP_LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_drcd_run_details_18936/duse_master.tmp && \
mv /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_drcd_run_details_18936/duse_master.tmp /tmp/spalutla/adf_nightly_regr/2015-03-31/drc_drcd_run_details_18936/duse_master
